export { renderWeeklyCover } from './page-01-cover';
export { renderWeeklyContentsEditorial } from './page-02-contents-editorial';
export { renderWeeklyLeadStory } from './page-03-lead-story';
export { renderWeeklyKeySignals } from './page-04-key-signals';
export { renderWeeklyImplications } from './page-05-implications';
export { renderWeeklyEnterpriseIndustry } from './page-06-enterprise-industry';
export { renderWeeklyExecutiveBriefing } from './page-07-executive-briefing';
export { renderWeeklyOperatorsToolkit } from './page-08-operators-toolkit';
export { renderWeeklyStrategicOutlook } from './page-09-strategic-outlook';
export { renderWeeklyClosing } from './page-10-closing';

export type { WeeklyCoverData } from './page-01-cover';
export type { WeeklyContentsEditorialData } from './page-02-contents-editorial';
export type { WeeklyLeadStoryData } from './page-03-lead-story';
export type { WeeklyKeySignalsData, WeeklySignalItem } from './page-04-key-signals';
export type { WeeklyImplicationsData } from './page-05-implications';
export type { WeeklyEnterpriseIndustryData } from './page-06-enterprise-industry';
export type { WeeklyExecutiveBriefingData } from './page-07-executive-briefing';
export type { WeeklyOperatorsToolkitData } from './page-08-operators-toolkit';
export type { WeeklyStrategicOutlookData } from './page-09-strategic-outlook';
export type { WeeklyClosingData } from './page-10-closing';
